export enum CoreEnum {
    CATALOGUE_REPOSITORY='CATALOGUE_REPOSITORY',
    CUSTOMER_REPOSITORY ='CUSTOMER_REPOSITORY',
    SHOP_REPOSITORY='SHOP_REPOSITORY',
    ORDER_DETAIL_REPOSITORY='ORDER_DETAIL_REPOSITORY',
    PRODUCT_REPOSITORY = 'PRODUCT_REPOSITORY',
    EMPLOYEE_REPOSITORY= 'EMPLOYEE_REPOSITORY',
    ORDER_REPOSITORY = 'ORDER_REPOSITORY',
}
    